<?php
/**
 * Plugin Name: v-Profiler for WordPress
 * Description: Zero-dependency, ultra-performance debugger toolbar for WordPress sites running on vhttpd.
 * Version: 0.1.0
 * Author: guweigang
 */

declare(strict_types=1);

if (!defined('ABSPATH')) {
    exit;
}

// PHP 版本兼容性检测 (vhttpd runtime 要求 PHP >= 8.1)
if (version_compare(PHP_VERSION, '8.1.0', '<')) {
    add_action('admin_notices', static function (): void {
        echo '<div class="notice notice-error"><p>';
        echo '<strong>v-Profiler:</strong> This plugin requires PHP version 8.1.0 or higher. Your current PHP version is ' . esc_html(PHP_VERSION) . '.';
        echo '</p></div>';
    });
    return;
}

// 确保 autoloader 正常加载
if (!class_exists(\VHttpd\WordPress\Profiler::class)) {
    $autoload = getenv('VHTTPD_PHP_PACKAGE_AUTOLOAD');
    if ((!is_string($autoload) || $autoload === '') && defined('VHTTPD_PHP_PACKAGE_AUTOLOAD')) {
        $autoload = (string) VHTTPD_PHP_PACKAGE_AUTOLOAD;
    }
    if (is_string($autoload) && $autoload !== '' && is_file($autoload)) {
        require_once $autoload;
    } else {
        $vhttpdVendor = getenv('VHTTPD_VENDOR');
        if (is_string($vhttpdVendor) && $vhttpdVendor !== '' && is_file($vhttpdVendor . '/vendor/autoload.php')) {
            require_once $vhttpdVendor . '/vendor/autoload.php';
        } elseif (is_file('/Users/guweigang/Source/vhttpd/php/package/vendor/autoload.php')) {
            require_once '/Users/guweigang/Source/vhttpd/php/package/vendor/autoload.php';
        } elseif (is_file(dirname(__DIR__) . '/vendor/autoload.php')) {
            require_once dirname(__DIR__) . '/vendor/autoload.php';
        }
    }
}

use VHttpd\WordPress\Profiler;

// 1. 全局调试日志函数
if (!function_exists('v_debug')) {
    function v_debug(mixed $var, string $label = ''): void {
        Profiler::log($var, $label, 'debug');
    }
}

if (!function_exists('v_log')) {
    function v_log(string $message, string $label = ''): void {
        Profiler::log($message, $label, 'info');
    }
}

// 2. 尽早开启遥测（捕获插件加载早期的错误与耗时）
Profiler::start();

// 挂载到非常早的过滤器，在 php-worker 模式下，每次请求开始时都会触发
add_filter('determine_current_user', static function ($userId) {
    Profiler::start();
    return $userId;
}, 1);

// 3. 在 init 阶段校验用户身份
add_action('init', static function (): void {
    $debug = defined('WP_DEBUG') && WP_DEBUG;

    // 检查是否全局关闭了挂件
    if (get_option('v_profiler_widget_enabled', 'yes') !== 'yes') {
        Profiler::stopAndDeactivate();
        return;
    }
    
    $secretToken = get_option('v_profiler_secret_token');
    $hasDebugCookie = !empty($secretToken) && isset($_COOKIE['v_profiler_session']) && $_COOKIE['v_profiler_session'] === $secretToken;
    $canManage = current_user_can('manage_options') || $hasDebugCookie;
    
    // 写入诊断日志，方便查看激活状态
    error_log(sprintf(
        '[v-Profiler] Auth Check: WP_DEBUG=%s, current_user_can(manage_options)=%s, has_debug_cookie=%s, request_uri=%s',
        $debug ? 'true' : 'false',
        current_user_can('manage_options') ? 'true' : 'false',
        $hasDebugCookie ? 'true' : 'false',
        $_SERVER['REQUEST_URI'] ?? 'unknown'
    ));

    if ($debug && $canManage) {
        Profiler::activate();
    } else {
        // 普通访客或调试关闭时，立即停止采集并撤销错误捕获
        Profiler::stopAndDeactivate();
    }
}, 99);

// 4. 引入后台管理模块
if (is_admin()) {
    require_once __DIR__ . '/v-profiler/v-profiler-admin.php';
}

// 5. 注册激活与停用钩子以自动配置 MU-Plugin Loader
register_activation_hook(__FILE__, 'v_profiler_activate_plugin');
register_deactivation_hook(__FILE__, 'v_profiler_deactivate_plugin');

function v_profiler_activate_plugin(): void {
    // 1. 生成 MU-Plugin Loader
    $muDir = defined('WPMU_PLUGIN_DIR') ? WPMU_PLUGIN_DIR : (defined('WP_CONTENT_DIR') ? WP_CONTENT_DIR . '/mu-plugins' : ABSPATH . 'wp-content/mu-plugins');
    if (!is_dir($muDir)) {
        @mkdir($muDir, 0755, true);
    }
    
    $loaderFile = $muDir . '/v-profiler-loader.php';
    $loaderContent = <<<'PHP'
<?php
/**
 * Plugin Name: v-Profiler Loader
 * Description: High-performance MUST-USE loader for v-Profiler telemetry module (vhttpd).
 * Version: 0.1.0
 * Author: guweigang
 *
 * Auto-generated by v-Profiler plugin. Do not edit directly.
 */
declare(strict_types=1);

if (file_exists(WP_PLUGIN_DIR . '/v-profiler/v-profiler.php')) {
    require_once WP_PLUGIN_DIR . '/v-profiler/v-profiler.php';
}
PHP;
    
    @file_put_contents($loaderFile, $loaderContent);

    // 2. 智能环境判定与自动开启极速模式
    $isVHttpd = false;
    $serverSoftware = $_SERVER['SERVER_SOFTWARE'] ?? '';
    if (str_contains(strtolower($serverSoftware), 'vhttpd') 
        || getenv('VHTTPD_DB_SOCKET') !== false 
        || getenv('VHTTPD_CACHE_SOCKET') !== false
        || getenv('VHTTPD_INTERNAL_ADMIN_SOCKET') !== false
    ) {
        $isVHttpd = true;
    }

    $savedMode = get_option('v_profiler_mode');
    if ($savedMode === false) {
        $savedMode = $isVHttpd ? 'full' : 'restricted';
        update_option('v_profiler_mode', $savedMode);
    }

    // 如果处于极速模式（或者是默认决定的极速模式），且文件不在，自动拷贝部署
    if ($savedMode === 'full') {
        $contentDir = defined('WP_CONTENT_DIR') ? WP_CONTENT_DIR : (defined('ABSPATH') ? ABSPATH . 'wp-content' : '');
        if ($contentDir !== '' && is_writable($contentDir)) {
            $db_src = __DIR__ . '/v-profiler/db.php';
            $db_dst = $contentDir . '/db.php';
            $oc_src = __DIR__ . '/v-profiler/object-cache.php';
            $oc_dst = $contentDir . '/object-cache.php';
            
            if (is_file($db_src) && !is_file($db_dst)) {
                @copy($db_src, $db_dst);
            }
            if (is_file($oc_src) && !is_file($oc_dst)) {
                @copy($oc_src, $oc_dst);
            }
        }
    }
}

function v_profiler_deactivate_plugin(): void {
    // 1. 清理 MU-Plugin Loader
    $muDir = defined('WPMU_PLUGIN_DIR') ? WPMU_PLUGIN_DIR : (defined('WP_CONTENT_DIR') ? WP_CONTENT_DIR . '/mu-plugins' : ABSPATH . 'wp-content/mu-plugins');
    $loaderFile = $muDir . '/v-profiler-loader.php';
    if (is_file($loaderFile)) {
        @unlink($loaderFile);
    }

    // 2. 清理 wp-content 下的 Drop-ins 数据库和缓存重构文件，防止插件删除后网站白屏崩溃
    $contentDir = defined('WP_CONTENT_DIR') ? WP_CONTENT_DIR : (defined('ABSPATH') ? ABSPATH . 'wp-content' : '');
    if ($contentDir !== '') {
        $dbFile = $contentDir . '/db.php';
        if (is_file($dbFile)) {
            $dbContent = @file_get_contents($dbFile);
            if ($dbContent !== false && str_contains($dbContent, 'VHttpd\\WordPress\\Wpdb')) {
                @unlink($dbFile);
            }
        }

        $ocFile = $contentDir . '/object-cache.php';
        if (is_file($ocFile)) {
            $ocContent = @file_get_contents($ocFile);
            if ($ocContent !== false && str_contains($ocContent, 'VHttpd\\WordPress\\ObjectCache')) {
                @unlink($ocFile);
            }
        }
    }
}

