[book]
title = "vhttpd 文档"
authors = ["vhttpd Contributors"]
language = "zh"
src = "book-src"

[output.html]
site-url = "/"
no-section-label = true
mathjax-support = false
smart-punctuation = true
default-theme = "light"
preferred-dark-theme = "navy"
